# Generated by Django 3.0 on 2019-12-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Linux', 'Linux'), ('Hacking', 'Hacking'), ('BlockChain', 'BlockChain')], max_length=12)),
                ('subtopico', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('post', models.TextField()),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
